### ISSUE TITLE
Add geo to Generate Synthetic Data pipeline

### ISSUE THREAD

**Issue by andreifoldes** [digital-wellbeing/platform-study-rr#10]
The `0_generateSyntheticData.qmd` is awesome, but we could add Geo...

- [ ] Save separate UK and US version of `synPanel` with separate `Geo` value - this will unfortunately duplicate everything

**Comment by nballou** [comment]
geo is part of Intake at the moment (named `region`), so you can do 

```
panel <- read_csv("data-synthetic/synPanel.csv") |> 
  left_join(read_csv("data-synthetic/synIntake.csv"), by = "pid") |> 
  filter(region == "US")

```
does that meet your needs or do you need them saved separately?

**Comment by andreifoldes** [comment]
Ah yes thank you! I missed that!
