### ISSUE TITLE
Use renv instead of pacman

### ISSUE THREAD

**Issue by mvuorre** [digital-wellbeing/platform-study-rr#4]
https://github.com/digital-wellbeing/platform-study-rr/blob/c93d48f9129d23b884c4737ffb386420e3889b9c/9_processScreenshots.qmd#L31

May I suggest using [renv](https://rstudio.github.io/renv/articles/renv.html) instead of pacman so running the scripts won't mess up my R installation & other projects?

**Comment by nballou** [comment]
oh are those not compatible? Was already using renv but I'll switch back to normal library calls

**Comment by nballou** [comment]
from the docs:
> renv also supports package loading with [box](https://cran.r-project.org/package=box) (box::use(...)) and [pacman](https://cran.r-project.org/package=pacman) (pacman::p_load(...)) 

did you have problems with this?

**Comment by mvuorre** [comment]
Oh, that is good! I didn't know renv supports pacman. All good, sorry!
