### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by mvuorre** [digital-wellbeing/platform-study-rr#6]
Two things would be great:

- [ ] Ensuring this reproduces & if not explain exactly what user must do
- [ ] Workflow instructions
  - e.g. Makefile / _quarto.yml / similar for one-click reproducibility (things like order in which scripts are run...)

Of course only if time budgets allow. These are great to have if you want someone else to be able to run code for e.g. providing feedback etc.

**Comment by mvuorre** [comment]
I tried to reproduce:

```r
renv::restore()
```

**Comment by nballou** [comment]
latest commit should be a step in the right direction - adds _quarto.yml, and `quarto render` worked for me to compile 0_generateSyntheticData.qmd, 1_preprocess.qmd, and 2_basicNeeds.qmd (as other analysis scripts aren't finished yet)

working on (a) getting it to deploy to GitHub pages for easier reading and (b) adding an option for external users to skip rendering 0_generateSyntheticData - however, we'd need to store the synthetic data on Github or else for this to work. None of the files are >100mb so in theory this is no problem

**Comment by andreifoldes** [comment]
We could also bring in https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage for the data files

**Comment by andreifoldes** [comment]
> latest commit should be a step in the right direction - adds _quarto.yml, and `quarto render` worked for me to compile 0_generateSyntheticData.qmd, 1_preprocess.qmd, and 2_basicNeeds.qmd (as other analysis scripts aren't finished yet)
> 
> working on (a) getting it to deploy to GitHub pages for easier reading and (b) adding an option for external users to skip rendering 0_generateSyntheticData - however, we'd need to store the synthetic data on Github or else for this to work. None of the files are >100mb so in theory this is no problem

Would be cool if you could try my analysis too!

**Comment by nballou** [comment]
excellent, will give it a go!
