### ISSUE TITLE
Error: Invalid grouping factor specification, pid

### ISSUE THREAD

**Issue by rpsychologist** [digital-wellbeing/platform-study-rr#8]
https://github.com/digital-wellbeing/platform-study-rr/blob/a4287b0ffaa2b96f61b4f23d4928cea48c95bd76/2_basicNeeds.qmd#L85-L89

**Comment by nballou** [comment]
fixed in 9f4ed2c - I'd updated the measure because a new paper came out, but didn't fix the recoding of the response scale so all globalNS values were NA. working now
